
# NumPy exercises


In [ ]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.19.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [ ]:
# your code goes here
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])



### Create a numpy array with values ranging from 10 to 49

In [ ]:
# your code goes here
b=np.arange(10,49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])



### Create a numpy matrix of 2*2 integers, filled with ones.

In [ ]:
# your code goes here
c=np.full((2,2),1,int)
c

array([[1, 1],
       [1, 1]])



### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [ ]:
# your code goes here
d=np.full((3,2),1,float)
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])



### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
# your code goes here
X=np.array([[1,2],[3,4]])
Y=np.full(X.shape,1,X.dtype)
Y

array([[1, 1],
       [1, 1]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [ ]:
# your code goes here
Z=np.zeros(X.shape,X.dtype)
Z

array([[0, 0],
       [0, 0]])



### Create a numpy matrix of 4*4 integers, filled with fives.

In [ ]:
# your code goes here
e=np.full((4,4),5,int)
e

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])



### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [ ]:
# your code goes here
n=np.random.randint(5) 
m=np.random.randint(4)
X=np.random.randint(0,100,(n,m))
print(X)
W=np.full(X.shape,7,int)
print(W)

[[44 11]
 [99 73]
 [ 5 67]]
[[7 7]
 [7 7]
 [7 7]]




### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [ ]:
# your code goes here
I=np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [ ]:
# your code goes here
r=np.random.randint(1,10,3)
r

array([5, 3, 3])



### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [ ]:
# your code goes here
rr=np.random.randint(0,100,(3,3,3))
rr

array([[[36, 74, 22],
        [40, 46, 31],
        [41, 84, 92]],

       [[96,  2, 75],
        [35, 40, 14],
        [ 8, 66, 25]],

       [[ 1, 32, 42],
        [24, 33, 37],
        [98, 71, 14]]])



### Given the X python list convert it to an Y numpy array

In [ ]:
# your code goes here
X=list(np.random.randint(0,100,5))
Y=np.array(X)
Y
type(Y)

numpy.ndarray



### Given the X numpy array, make a copy and store it on Y.

In [ ]:
# your code goes here
X=Y
print(X)
id(X)==id(Y)
Z=X.copy()
Z+=1
print(Z)


[89 94 43 34 75]
[90 95 44 35 76]




### Create a numpy array with numbers from 1 to 10

In [ ]:
# your code goes here
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



### Create a numpy array with the odd numbers between 1 to 10

In [ ]:
# your code goes here
arr2=np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])



### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [ ]:
# your code goes here
m=np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])



### Show the memory size of the given Z numpy matrix

In [ ]:
# your code goes here
from sys import getsizeof
l=getsizeof(m)
print("size of the previous matric in bytes is",l)

size of the previous matric in bytes is 112


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [ ]:
# your code goes here
X=np.array([1,3,7,9,6])
X[0]

1



### Given the X numpy array, show it's last element

In [ ]:
# your code goes here
X[-1]

6



### Given the X numpy array, show it's first three elements

In [ ]:
# your code goes here
X[:3]

array([1, 3, 7])



### Create a numpy array with numbers from 1 to 10, in descending order.

In [ ]:
# your code goes here
A=np.arange(10,0,-1)
A

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])



### Given the X numpy array, show all middle elements

In [ ]:
# your code goes here
X[1:-1]

array([3, 7, 9])



### Given the X numpy array, show the elements in reverse position

In [ ]:
# your code goes here
X[::-1]

array([6, 9, 7, 3, 1])



### Given the X numpy array, show the elements in an odd position

In [ ]:
# your code goes here
print(X)
X[1:10:2]

[1 3 7 9 6]


array([3, 9])



### Given the X numpy matrix, show the first row elements

In [ ]:
# your code goes here
X=np.arange(10).reshape(2,5)
print(X[0])

[0 1 2 3 4]




### Given the X numpy matrix, show the last row elements

In [ ]:
# your code goes here
print(X[-1])

[5 6 7 8 9]




### Given the X numpy matrix, show the first element on first row

In [ ]:
# your code goes here
X[0,0]

0



### Given the X numpy matrix, show the last element on last row

In [ ]:
# your code goes here
X[-1,-1]

9



### Given the X numpy matrix, show the middle row elements

In [ ]:
# your code goes here
def show_middle_row(matrix):
  if matrix.shape[0]<=2:
    print("no middle row")
  elif matrix.shape[0]%2==0:
    print("no middle row")
  else:
    return X[int((matrix.shape[0]-1)/2)]
X=np.arange(10).reshape(5,2)
print(show_middle_row(X))

[4 5]




### Given the X numpy matrix, show the first two elements on the first two rows

In [ ]:
# your code goes here
X=np.arange(25).reshape(5,5)
X
print(X[0:2,0:2])

[[0 1]
 [5 6]]




### Given the X numpy matrix, show the last two elements on the last two rows

In [ ]:
# your code goes here
print(X[-2:,-2:])

[[18 19]
 [23 24]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [ ]:
# your code goes here
X=np.random.randint(0,100,4,int)
Y=X.astype(float)
print(Y)
X.dtype

[94.  4. 13. 38.]


dtype('int64')



### Reverse the given numpy array (first element becomes last)

In [ ]:
# your code goes here
X=np.random.randint(0,100,4,int)
print(X)
print(X[::-1])
#or using the .flip() method
print(np.flip(X))

[25 32 23 30]
[30 23 32 25]
[30 23 32 25]




### Order (sort) the given numpy array

In [ ]:
# your code goes here
X=np.array([1,5,3,9])
Y=np.sort(X)
Y

array([1, 3, 5, 9])



### Given the X numpy array, set the fifth element equal to 1

In [ ]:
# your code goes here
X=np.array([1,3,6,7,5,0])
X[4]=1
X


array([1, 3, 6, 7, 1, 0])



### Given the X numpy array, change the 50 with a 40

In [ ]:
# your code goes here
X=np.arange(0,100,10)
X=np.where(X==50,40,X)
print(X)

[ 0 10 20 30 40 40 60 70 80 90]



### Given the X numpy matrix, change the last row with all 1

In [ ]:
# your code goes here
X=np.arange(9).reshape(3,3)
X[-1]=1
X

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 1]])


### Given the X numpy matrix, change the last item on the last row with a 0

In [ ]:
# your code goes here
X[-1,-1]=0
X

array([[0, 1, 2],
       [3, 4, 5],
       [1, 1, 0]])


### Given the X numpy matrix, add 5 to every element

In [ ]:
# your code goes here
X+5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [ 6,  6,  5]])


## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [ ]:
# your code goes here
X=np.array([1,-5,7,9])

X<0

array([False,  True, False, False])


### Given the X numpy array, get the negative elements

In [ ]:
# your code goes here
X[X<0]

array([-5])


### Given the X numpy array, get numbers higher than 5

In [ ]:
# your code goes here
X[X>5]

array([7, 9])


### Given the X numpy array, get numbers higher than the elements mean

In [ ]:
# your code goes here
X[X>X.mean()]

array([7, 9])


### Given the X numpy array, get numbers equal to 2 or 10

In [ ]:
# your code goes here
X=np.array([1,2,10])
X[(X==2) | (X==10)]

array([ 2, 10])


## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [ ]:
# your code goes here
X.all() != 0

True


## Summary statistics

### Given the X numpy array, show the sum of its elements

In [ ]:
# your code goes here
X.sum()

13


### Given the X numpy array, show the mean value of its elements

In [ ]:
# your code goes here
X.mean()

4.333333333333333


### Given the X numpy matrix, show the sum of its columns

In [ ]:
# your code goes here
X=np.full((2,3),1)
X.sum(axis=0)

array([2, 2, 2])


### Given the X numpy matrix, show the mean value of its rows

In [ ]:
# your code goes here
X=np.array([[1,2,3],[4,5,6]])
X.mean(axis=1)

array([2., 5.])

### Given the X numpy array, show the max value of its elements

In [ ]:
X=np.arange(10)
X.max()

9

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



# Answer The following questions!

In [ ]:
# your code goes here
import seaborn as sns

In [ ]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df.head(100)

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0          0       3    male  22.0  ...   NaN  Southampton     no  False
1          1       1  female  38.0  ...     C    Cherbourg    yes  False
2          1       3  female  26.0  ...   NaN  Southampton    yes   True
3          1       1  female  35.0  ...     C  Southampton    yes  False
4          0       3    male  35.0  ...   NaN  Southampton     no   True
..       ...     ...     ...   ...  ...   ...          ...    ...    ...
95         0       3    male   NaN  ...   NaN  Southampton     no   True
96         0       1    male  71.0  ...     A    Cherbourg     no   True
97         1       1    male  23.0  ...     D    Cherbourg    yes  False
98         1       2  female  34.0  ...   NaN  Southampton    yes  False
99         0       2    male  34.0  ...   NaN  Southampton     no  False

[100 rows x 15 columns]

In [ ]:
df_child=df[df.who=='child']
df_child['age'].mean()
df_child['age'].fillna(df_child['age'].mean(),inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [ ]:
#Cleaning
df['age'].fillna(df['age'].mean(),inplace=True)
df['deck'].fillna(df['deck'].mode(),inplace=True)
df

survived  pclass     sex        age  ...  deck  embark_town  alive  alone
0           0       3    male  22.000000  ...     C  Southampton     no  False
1           1       1  female  38.000000  ...     C    Cherbourg    yes  False
2           1       3  female  26.000000  ...   NaN  Southampton    yes   True
3           1       1  female  35.000000  ...     C  Southampton    yes  False
4           0       3    male  35.000000  ...   NaN  Southampton     no   True
..        ...     ...     ...        ...  ...   ...          ...    ...    ...
886         0       2    male  27.000000  ...   NaN  Southampton     no   True
887         1       1  female  19.000000  ...     B  Southampton    yes   True
888         0       3  female  29.699118  ...   NaN  Southampton     no  False
889         1       1    male  26.000000  ...     C    Cherbourg    yes   True
890         0       3    male  32.000000  ...   NaN   Queenstown     no   True

[891 rows x 15 columns]

# Average age of woman category.

In [ ]:
df[df.who=='woman'].age.mean()

31.550011938354697

## Average age of man category.

In [ ]:
df[df.who=='man'].age.mean()

32.37093219410664

## The lowest age among alone woman.

In [ ]:
df[(df.who=='woman') & (df.alone==True)].age.min()

16.0

# The highest pulse among running student and not fat category. 

In [ ]:
df2 = sns.load_dataset('exercise')
df2.head(100)
df2[(df2.kind=='running') & (df2.diet=='no fat')].pulse.max()

150

# Sort the DataFrame in ascending order of the 'age' use sort values (df.sort_values(by='...', ascending=...)). 

In [ ]:
df.sort_values(by='age',ascending=True)

survived  pclass     sex    age  ...  deck  embark_town  alive  alone
803         1       3    male   0.42  ...   NaN    Cherbourg    yes  False
755         1       2    male   0.67  ...   NaN  Southampton    yes  False
644         1       3  female   0.75  ...   NaN    Cherbourg    yes  False
469         1       3  female   0.75  ...   NaN    Cherbourg    yes  False
831         1       2    male   0.83  ...   NaN  Southampton    yes  False
..        ...     ...     ...    ...  ...   ...          ...    ...    ...
116         0       3    male  70.50  ...   NaN   Queenstown     no   True
96          0       1    male  71.00  ...     A    Cherbourg     no   True
493         0       1    male  71.00  ...   NaN    Cherbourg     no   True
851         0       3    male  74.00  ...   NaN  Southampton     no   True
630         1       1    male  80.00  ...     A  Southampton    yes   True

[891 rows x 15 columns]